name = "QFT"
uuid = "49c623b1-9a12-4bf7-99dd-267ae146fd9d"
authors = ["CianLM"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
